version: 1.0
app:
  instances:
    min: 1
    max: 2
  # configure endpoints
  endpoints: public
  version: f5fb8675-9f6d-4afe-b05e-0e29c43db418
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
    - name: testValue
      value: "testData"
